fixing DKTEST for DKBash

diff --git a/DKBash/functions/DK b/DKBash/functions/DK
--- a/DKBash/functions/DK
+++ b/DKBash/functions/DK
@@ -4,104 +4,117 @@ echo "DK($*)"
 #echo "* = $*"
 #echo "@ = $@"
 
-
-
-	[ -z ${ENABLE_DKTEST} ] && export ENABLE_DKTEST=0
-	#echo "DKSCRIPT_PATH = $DKSCRIPT_PATH"
-	#echo "BASH_SOURCE = ${BASH_SOURCE[@]}"
-	#echo "BASH_SOURCE[0] = ${BASH_SOURCE[0]}"
-	#echo "BASH_SOURCE[1] = ${BASH_SOURCE[1]}"
+[ -z ${ENABLE_DKTEST} ] && export ENABLE_DKTEST=1
+#echo "BASH_SOURCE = ${BASH_SOURCE[@]}"
+#echo "BASH_SOURCE[0] = ${BASH_SOURCE[0]}"
+#echo "BASH_SOURCE[1] = ${BASH_SOURCE[1]}"
 	
-	#export PS4=$'+\e[33m ${BASH_SOURCE[0]:-nofile}:${BASH_LINENO[0]:-noline} ${FUNCNAME[0]:-nofunc}()\e[0m  '
+#export PS4=$'+\e[33m ${BASH_SOURCE[0]:-nofile}:${BASH_LINENO[0]:-noline} ${FUNCNAME[0]:-nofunc}()\e[0m  '
 
-	###### Reload Main Script with bash ######
-	if [ ${RELOAD_WITH_BASH-1} = 1 ]; then
-		export RELOAD_WITH_BASH=0
-		if [ -n "$(command -v bash)" ]; then
-			echo "reloading with /bin/bash . . ."
-			echo "SHLVL = $SHLVL"
-			exec /bin/bash "$0"
-			echo "SHLVL = $SHLVL"
-		else
-			echo ""
-			echo "ERROR: This script requires bash. Please install it and try again.";
-			read -rp 'Press enter to exit...' key;
-			exit 1
-		fi
+###### Reload Main Script with bash ######
+if [ ${RELOAD_WITH_BASH-1} = 1 ]; then
+	export RELOAD_WITH_BASH=0
+	if [ -n "$(command -v bash)" ]; then
+		echo "reloading with /bin/bash . . ."
+		echo "SHLVL = $SHLVL"
+		exec /bin/bash "$0"
+		echo "SHLVL = $SHLVL"
+	else
+		echo ""
+		echo "ERROR: This script requires bash. Please install it and try again.";
+		read -rp 'Press enter to exit...' key;
+		exit 1
 	fi
-	[ -n "$DKINIT" ] && return || export readonly DKINIT=1
+fi
+[ -n "$DKINIT" ] && return || export readonly DKINIT=1
 	
-#	if $(ps -o >/dev/null 2>&1);then  
-#		THIS_PATH=$(ps -o args= $PID | tail -n 6 | awk 'FNR==1 {print $2}')
-#		$echo "    THIS_PATH = $THIS_PATH"
-#		PARENT_PATH=$(ps -o args= $PPID | awk '{print $2}')
-#		$echo "    PARENT_PATH = $PARENT_PATH"
-#	else
-#		#echo "ps -o NOT AVAILABLE"
-#		echo $(ps -p -f $PPID)
-#	fi
+#if $(ps -o >/dev/null 2>&1);then  
+#	THIS_PATH=$(ps -o args= $PID | tail -n 6 | awk 'FNR==1 {print $2}')
+#	$echo "    THIS_PATH = $THIS_PATH"
+#	PARENT_PATH=$(ps -o args= $PPID | awk '{print $2}')
+#	$echo "    PARENT_PATH = $PARENT_PATH"
+#else
+#	#echo "ps -o NOT AVAILABLE"
+#	echo $(ps -p -f $PPID)
+#fi
 
-	###### get DKSCRIPT_ variables  ######
-	#[ -n "$1" ] && DKSCRIPT_PATH=$(realpath $1) || export DKSCRIPT_PATH=$(pwd)/$(basename $0)
-	export DKSCRIPT_PATH=$(pwd)/$(basename $0)
-	[ -e $DKSCRIPT_PATH ] || dk_error "DKSCRIPT_PATH:${DKSCRIPT_PATH} does not exist"
-	echo "DKSCRIPT_PATH = $DKSCRIPT_PATH"
-	[ -n "$(command -v "cygpath")" ] && DKSCRIPT_PATH=$(cygpath -u "$DKSCRIPT_PATH")
-	export DKSCRIPT_DIR=$(dirname $DKSCRIPT_PATH)
-	echo "DKSCRIPT_DIR = $DKSCRIPT_DIR"
-	export DKSCRIPT_NAME=$(basename $DKSCRIPT_PATH)
-	echo "DKSCRIPT_NAME = $DKSCRIPT_NAME"
+###### get DKSCRIPT_ variables  ######
+echo "\$0 = $0"
+#[ -e $0 ] && export DKSCRIPT_PATH=$0
 
+echo "\$(realpath \$0) = $(realpath $0)"
+[ -e $(realpath $0) ] && export DKSCRIPT_PATH=$(realpath $0)
 
-	###### Set and check posix mode ######
-	$(set -o posix) && set -o posix && case :$SHELLOPTS: in
-	  *:posix:*) echo "POSIX mode enabled" ;;
-	  *)         echo "POSIX mode not enabled" ;;
-	esac
+#echo "\$(pwd)/\$(basename \$0) = $(pwd)/$(basename $0)"
+#[ -e $(pwd)/$(basename $0) ] && export DKSCRIPT_PATH=$(pwd)/$(basename $0)
 
+[ -n "$(command -v "cygpath")" ] && DKSCRIPT_PATH=$(cygpath -u "${DKSCRIPT_PATH}")
+[ -e ${DKSCRIPT_PATH} ] || $(echo "DKSCRIPT_PATH:${DKSCRIPT_PATH} does not exist"; read -rp 'Press enter to continue...' key; exit)
+echo "\${DKSCRIPT_PATH} = ${DKSCRIPT_PATH}"
 
-	###### Set error trace options ######
-	#shopt -s expand_aliases
-	$(set -o pipefail) && set -o pipefail  	# trace ERR through pipes
-	$(set -o errtrace) && set -o errtrace 	# trace ERR through 'time command' and other functions
-	#$(set -o nounset) && set -o nounset  	# set -u : exit the script if you try to use an uninitialised variable
-	#$(set -o errexit) && set -o errexit  	# set -e : exit the script if any statement returns a non-true
+export DKSCRIPT_DIR=$(dirname ${DKSCRIPT_PATH})
+echo "DKSCRIPT_DIR = ${DKSCRIPT_DIR}"
+
+export DKSCRIPT_NAME=$(basename ${DKSCRIPT_PATH})
+echo "DKSCRIPT_NAME = ${DKSCRIPT_NAME}"
 
 
-	###### set true and false variables ######
-	export readonly true=0
-	export readonly false=1
+###### Set and check posix mode ######
+$(set -o posix) && set -o posix && case :$SHELLOPTS: in
+  *:posix:*) echo "POSIX mode enabled" ;;
+  *)         echo "POSIX mode not enabled" ;;
+esac
 
 
-	###### get DKBASH_DIR ######
-	export BASH_SOURCE_DIR=$( cd -- "$(dirname "$BASH_SOURCE")" >/dev/null 2>&1 ; pwd -P )
-	export DKBASH_DIR=$( cd -- "$(dirname "$BASH_SOURCE_DIR")" >/dev/null 2>&1 ; pwd -P )
-	echo "DKBASH_DIR = $DKBASH_DIR"
+###### Set error trace options ######
+#shopt -s expand_aliases
+$(set -o pipefail) && set -o pipefail  	# trace ERR through pipes
+$(set -o errtrace) && set -o errtrace 	# trace ERR through 'time command' and other functions
+#$(set -o nounset) && set -o nounset  	# set -u : exit the script if you try to use an uninitialised variable
+#$(set -o errexit) && set -o errexit  	# set -e : exit the script if any statement returns a non-true
+
+
+###### set true and false variables ######
+export readonly true=0
+export readonly false=1
+
+
+###### get DKBASH_DIR ######
+export BASH_SOURCE_DIR=$( cd -- "$(dirname "$BASH_SOURCE")" >/dev/null 2>&1 ; pwd -P )
+export DKBASH_DIR=$( cd -- "$(dirname "$BASH_SOURCE_DIR")" >/dev/null 2>&1 ; pwd -P )
+echo "DKBASH_DIR = $DKBASH_DIR"
 	
-	chmod 777 ${DKBASH_DIR}/functions/*
+chmod 777 ${DKBASH_DIR}/functions/*
+export PATH=${PATH}:${DKBASH_DIR}/functions
 	
-	###### Script loader ######
-	#if [ -n "$ENABLE_dk_load" ]; then
-		###### aquire if missing ######
-		[ ! -e ${DKBASH_DIR}/functions/dk_load ] && wget -P DKBash/functions https://raw.githubusercontent.com/aquawicket/Digitalknob/Development/DKBash/functions/dk_load
-		[ ! -e ${DKBASH_DIR}/functions/dk_load ] && curl -Lo DKBash/functions/dk_load https://raw.githubusercontent.com/aquawicket/Digitalknob/Development/DKBash/functions/dk_load
+###### Script loader ######
+#if [ -n "$ENABLE_dk_load" ]; then
+	###### download if missing ######
+	[ ! -e ${DKBASH_DIR}/functions/dk_load ] && wget -P DKBash/functions https://raw.githubusercontent.com/aquawicket/Digitalknob/Development/DKBash/functions/dk_load
+	[ ! -e ${DKBASH_DIR}/functions/dk_load ] && curl -Lo DKBash/functions/dk_load https://raw.githubusercontent.com/aquawicket/Digitalknob/Development/DKBash/functions/dk_load
 	
-		. ${DKBASH_DIR}/functions/dk_load
-		dk_load dk_escapeSequences && dk_escapeSequences
-		dk_load $DKSCRIPT_PATH
-	#else	
-	#	dk_escapeSequences
-	#fi
-	export PATH=${PATH}:${DKBASH_DIR}/functions
-
+	. ${DKBASH_DIR}/functions/dk_load
+	dk_load ${DKBASH_DIR}/dk_escapeSequences && dk_escapeSequences
+	dk_load ${DKSCRIPT_PATH}
+#else	
+#dk_escapeSequences
+#fi
+	
 	
 #	dk_load dk_bundleSource
 #	dk_bundleSource $dk_load_list builder_bundle.sh
 
-#	###### DKTEST MODE ######
-#	echo "$DKBASH_DIR/functions  $DKSCRIPT_DIR"
-#	if [ "$DKBASH_DIR/functions" = "$DKSCRIPT_DIR" ]; then
-#		[ "${ENABLE_DKTEST}" = "1" ] && export DKTEST=${BASH_SOURCE[1]} || echo "DISABLE_DKTEST"
-#	fi
-#	
-#	#echo "DK($*)"
+###### DKTEST MODE ######
+if [ "${ENABLE_DKTEST}" = "1" ]; then
+	if [ "${DKSCRIPT_DIR}" = "${DKBASH_DIR}/functions" ]; then
+		echo ""
+		echo "###### DKTEST MODE ###### ${DKSCRIPT_NAME} ###### DKTEST MODE ######"
+		echo ""
+		DKTEST
+		echo ""
+		echo "########################## END TEST ################################"
+		echo ""
+		read -rp 'Press enter to continue...' key
+		exit
+	fi
+fi
diff --git a/DKBash/functions/dk_load b/DKBash/functions/dk_load
--- a/DKBash/functions/dk_load
+++ b/DKBash/functions/dk_load
@@ -1,6 +1,6 @@
 #!/bin/sh
-[ -n "$inclue_guard_dk_load" ] && return || readonly inclue_guard_dk_load=1
-[ -z "$DKINIT" ] && . ./DK
+[ -n "${inclue_guard_dk_load}" ] && return || readonly inclue_guard_dk_load=1
+[ -z "${DKINIT}" ] && . ./DK
 
 
 ##################################################################################
@@ -9,114 +9,104 @@
 #
 #
 dk_load() {
-	#echo "dk_load($*)"
 	#dk_debugFunc
+	#echo "dk_load($*)"
+	
 	local fn=
 	#fpath=
-	[ -z $1 ] && return 0 #true
+	[ -z $1 ] && return 0
 	
-	#echo "if [ -e "$1" ]; then"
 	if [ -e "$1" ]; then
 		fpath=$1
 		fn=$(basename ${fpath})
 	    fn="${fn%.*}"
 	else
 		fn="$1"
-		#echo "fn = ${fn}"
-		#echo "DKBASH_DIR = ${DKBASH_DIR}"
-		#echo "fpath = ${fpath}"
 		fn=$(basename ${fn})
-		fpath=${DKBASH_DIR}/functions/$fn
-		#echo "fpath = ${fpath}"
+		fpath=${DKBASH_DIR}/functions/${fn}
 	fi
 	
-	#### downloader ####
-	[ ! -e $fpath ] && wget -P ${DKBASH_DIR}/functions https://raw.githubusercontent.com/aquawicket/Digitalknob/Development/DKBash/functions/${fn}
-	[ ! -e $fpath ] && curl -Lo ${DKBASH_DIR}/functions/${fn} https://raw.githubusercontent.com/aquawicket/Digitalknob/Development/DKBash/functions/${fn}
+	#### download if missing ####
+	[ ! -e ${fpath} ] && wget -P ${DKBASH_DIR}/functions https://raw.githubusercontent.com/aquawicket/Digitalknob/Development/DKBash/functions/${fn}
+	[ ! -e ${fpath} ] && curl -Lo ${DKBASH_DIR}/functions/${fn} https://raw.githubusercontent.com/aquawicket/Digitalknob/Development/DKBash/functions/${fn}
 	
 	# Convert to unix line endings if CRLF found
-	#if [ -e $fpath]; then
-		#if [[ $(file -b - < $fpath) =~ CRLF ]]; then		# BASH REGEX MATCH
-		if echo $(file -b - < $fpath) | grep -q CRLF; then	# POSIX REGEX MATCH
+	#if [ -e ${fpath}]; then
+		#if [[ $(file -b - < ${fpath}) =~ CRLF ]]; then		# BASH REGEX MATCH
+		if echo $(file -b - < ${fpath}) | grep -q CRLF; then	# POSIX REGEX MATCH
 			echo "Converting file to Unix line endings"
-			sed -i -e 's/\r$//' $fpath
+			sed -i -e 's/\r$//' ${fpath}
 		fi
 	#fi
 	
-	if [ -f $fpath ]; then
-		local ${fn}=$fpath
+	if [ -f ${fpath} ]; then
+		local ${fn}=${fpath}
     else
-        echo "$fpath: file not found"
+        echo "${fpath}: file not found"
 		return 1
     fi
 
-	if [[ $dk_load_list =~ ";$fn;" ]]; then			# BASH REGEX MATCH
-	#if echo $dk_load_list | grep -q "$fn;"; then		# POSIX REGEX MATCH
-        #echo "$fn: already in the list" 	# if already in list, do nothing
+	if [[ ${dk_load_list} =~ ";${fn};" ]]; then			# BASH REGEX MATCH
+	#if echo ${dk_load_list} | grep -q "${fn};"; then	# POSIX REGEX MATCH
+        #echo "${fn}: already in the list" 				# if already in list, do nothing
         return 0
     else
-		dk_load_list="${dk_load_list};$fn;" # Add to list
+		dk_load_list="${dk_load_list};${fn};" 			# Add to list
+		#echo "added ${fn} to dk_load_list"
 		
-		#echo "USING BASH ARRAYS"
-		oldIFS=$IFS
+		oldIFS=${IFS}
 		IFS=$'\n'
-		lines=( $(grep -E "(dk|DK)_[a-zA-Z0-9]*" $fpath) )
-		#IFS=$'\n' read -r -d '' -a lines < <( echo "$(grep -E "(dk|DK)_[a-zA-Z0-9]*" $fpath)" && printf '\0' )
-		IFS=$oldIFS
+		lines=( $(grep -E "(dk|DK)_[a-zA-Z0-9]*" ${fpath}) )
+		#IFS=$'\n' read -r -d '' -a lines < <( echo "$(grep -E "(dk|DK)_[a-zA-Z0-9]*" ${fpath})" && printf '\0' )
+		IFS=${oldIFS}
 		for value in "${lines[@]}"; do
 			#value=${value%%N*}   # cut off everything from the first N to end
-			#value=${value%N*}   # cut off everything from the last N to end
-			#value=${value#*N}   # cut off everything from begining to first N
+			#value=${value%N*}    # cut off everything from the last N to end
+			#value=${value#*N}    # cut off everything from begining to first N
 			#value=${value##*N}   # cut off everything from begining to last N
 				
-			value=${value//'$#'/}					# remove any $# before removing #comments
-			value=${value%%#*}						# remove everything after # (comments)
+			value=${value//'$#'/}					    # remove any $# before removing #comments
+			value=${value%%#*}						    # remove everything after # (comments)
 			
-			[[ $value =~ [Dd][Kk]_[A-Za-z0-9_]* ]]	# BASH REGEX MATCH
-			value=${BASH_REMATCH[0]}				# BASH REGEX VALUE
+			[[ ${value} =~ [Dd][Kk]_[A-Za-z0-9_]* ]]	# BASH REGEX MATCH
+			value=${BASH_REMATCH[0]}				    # BASH REGEX VALUE
 			
 #			for i in "${!BASH_REMATCH[@]}"; do
-#				echo "$i: ${BASH_REMATCH[$i]}"
+#				echo "$i: ${BASH_REMATCH[${i}]}"
 #			done
 			
-			#value=$(echo "$value" | grep -o "[Dd][Kk]_[A-Za-z0-9_]*" | head -1)	# POSIX REGEX MATCH
-			[ -z "$value" ] && continue
+			#value=$(echo "${value}" | grep -o "[Dd][Kk]_[A-Za-z0-9_]*" | head -1)	# POSIX REGEX MATCH
+			[ -z "${value}" ] && continue
 
-			#echo "${fn}: '$value'"
-			#echo "dk_load_list: $dk_load_list"	
-			if [[ $dk_load_list =~ ";$value;" ]]; then		# BASH REGEX MATCH
-			#if echo $dk_load_list | grep -q "$value;"; then	# POSIX REGEX MATCH
-				#echo "${fn}: skipping $value.    already in load_list"
-				#echo "dk_load_list = $dk_load_list"
+			if [[ ${dk_load_list} =~ ";${value};" ]]; then			# BASH REGEX MATCH
+			#if echo ${dk_load_list} | grep -q "${value};"; then	# POSIX REGEX MATCH
+				#echo "${fn}: skipping ${value}.    already in load_list"
 				continue
-			elif [[ ${fn} == $value ]]; then
-				#echo "${fn}: skipping $value.    already matches fn"
+			elif [ ${fn} = ${value} ]; then
+				#echo "${fn}: skipping ${value}.    already matches fn"
 				continue
 			# FIXME: this messes things up 
-			#elif [[ $(command -v $value) != "" ]]; then
-				#echo "${fn}: skipping $value.    command already recognized"
+			#elif ! [ $(command -v ${value}) = "" ]; then
+				#echo "${fn}: skipping ${value}.    command already recognized"
 				#continue
-			elif [[ "$value" == "" ]]; then
-				#echo "${fn}: skipping $value.    empty"
+			elif [ "${value}" = "" ]; then
+				#echo "${fn}: skipping ${value}.    empty"
 				continue
 			else
-				#echo "$fn: dk_load( $value )"
-				dk_load $value
+				dk_load ${value}
 			fi
 		done
 
 		if [ -f "${!fn}" ]; then
-			#echo "{@}: ${@}"
-			#echo "{fn}: ${!fn}"
-			if ! [ $@ == ${!fn} ]; then
-				#echo "$fn: source ${!fn}"
+			#if ! [ "${@}" = "${!fn}" ]; then
 				. "${!fn}"
-			fi
+				echo "Sourced ${!fn}"
+			#fi
 			#return 0
 		fi	
 	fi
 	
-	#echo "$dk_load_list" > dk_load_list.txt
+	#echo "${dk_load_list}" > dk_load_list.txt
 }
 
-#dk_load "$0"
+#dk_load "${0}"
