added DKBash function files

diff --git a/DKBash/functions/dk_extract b/DKBash/functions/dk_extract
--- a/DKBash/functions/dk_extract
+++ b/DKBash/functions/dk_extract
@@ -1,41 +1,56 @@
+#!/bin/sh
 #echo "$0 $*"
 #[ -n "$include_dk_test" ] && exit || export readonly include_dk_test=1
 [ -z "$DKINIT" ] && . ./DK
 
 
 ##################################################################################
-# dk_extract(<file> <destination>)
+# dk_extract(<file_path> <destination>)
 #
 #
 dk_extract () {
+	dk_debug "dk_extract($*)"
 	dk_debugFunc
-	[ $# -ne 2 ] && dk_error "Incorrect number of parameters"
+	[ $# -ne 2 ] && dk_error "dk_extract(): Incorrect number of parameters"
 
+	src="$1"
+	dest="$2"
+	
+	if ! dk_fileExists "${dest}"; then
+		dk_makeDirectory "${dest}"
+	fi
+	
+	tar -xf "${src}" -C "${dest}"
+	return
+	
+	
+	
+	
 	filename="$(basename "$1")"
 	destFolder="${filename%.*}"
 	destFolder="${destFolder%.*}"
 	fulldest="$2/$destFolder"
 	dk_printVar fulldest
 		
-	#if dk_fileExists $fulldest; then
-	#	dk_warning "dk_extract(): $fulldest already exists"
-	#	return 0
-	#fi
+	if dk_fileExists "${fulldest}"; then
+		dk_warning "dk_extract(): ${fulldest} already exists"
+		return
+	fi
 	dk_info "Extracting $1 . . ."
 	parentdir="$(dirname "$1")"
 	parentdest="$(dirname "$2")"
 	dk_printVar parentdir
 	dk_printVar filename
 	#need to cd into parent directory of $1 and send tar the file name of $1
-	olddir=$PWD
-	cd "$parentdir" #|| dk_error "cd $$parentdir failed!"
-	tar -xf "$filename" -C "$2"
-	cd "$oldpwd" #|| dk_error "cd $$oldpwd failed!"
-	dk_convertToCIdentifier "$destFolder" destFolder_
+	cd "${parentdir}" #|| dk_error "cd ${parentdir} failed!"
+	tar -xf "${filename}" -C "$2"
+	cd "${OLDPWD}" #|| dk_error "cd ${OLDPWD} failed!"
+	dk_convertToCIdentifier "${destFolder}" destFolder_
 	dk_printVar destFolder_
-	mv "$2"/"$destFolder" "$2"/"$destFolder_"
+	#mv "$2"/"${destFolder}" "$2"/"${destFolder}_"
+	dk_rename "$2"/"${destFolder}" "$2"/"${destFolder}_" 
 
-	#echo echo "$CMAKE_FOLDER">"$2"/"$destFolder_"/dk_installed
+	#echo echo "${CMAKE_FOLDER}">"$2"/"${destFolder}_"/dk_installed
 
 	#TODO
 	#[ "$input" = "" ]
