git commit

diff --git a/DKBash/functions/dk_removeAll b/DKBash/functions/dk_removeAll
--- a/DKBash/functions/dk_removeAll
+++ b/DKBash/functions/dk_removeAll
@@ -9,16 +9,19 @@
 #
 #
 dk_removeAll () {
+	echo "dk_removeAll($*)"
 	dk_debugFunc
 	[ $# -gt 1 ] && dk_error "Too many parameters"
 	
-	if ! [ "$1" = "wipe" ]; then	
+	if ! [ "$1" = "wipe" ]; then
 		clear
 		dk_echo
 		dk_echo
-		dk_echo "Do you want to remove the entire local repository . . . ?"
-		dk_echo "This will delete digitalknob, Save any changes"
-		dk_echo "you wish to commit or save beforehand."		
+		dk_info "Do you want to reset the entire local repository . . . ?"
+		dk_info "This will delete digitalknob, everything will be reset,"
+		dk_info "and the repository will be re-cloned. All libraries and tools"
+		dk_info "will be redk_downloaded and rebuild from start. Save any changes"
+		dk_info "you wish to commit or save beforehand."
 		dk_echo
 		
 		dk_confirm || return 0
@@ -26,19 +29,21 @@ dk_removeAll () {
 		# first we need to relocate this file up one directory
 		# make sure script is running from DKBRANCH_DIR
 		if ! [ "$DKSCRIPT_DIR" = "$DKBRANCH_DIR" ]; then
-			dk_echo "${yellow}"				
+			dk_echo "${yellow}"
 			dk_echo "WARNING: this file isn't running from the branch directory"
 			dk_echo "Is must be in the branch directory to continue."
 			dk_echo "DKSCRIPT_DIR = $DKSCRIPT_DIR"
 			dk_echo "${clr}"			
 			dk_printVar DKBRANCH_DIR
-			return 1;
+			return $false;
 		fi
 		
 		dk_info "RELOCATING SCRIPT TO -> $DIGITALKNOB_DIR/$DKSCRIPT_NAME"
-		cp "$DKSCRIPT_DIR"/"$DKSCRIPT_NAME" "$DIGITALKNOB_DIR"/"$DKSCRIPT_NAME"
-		exec "$DIGITALKNOB_DIR/$DKSCRIPT_NAME" dk_removeAll wipe
-		dk_exit
+		cp -r "$DKBRANCH_DIR/DKBash" "$DIGITALKNOB_DIR/DKBash"
+		cp "$DKSCRIPT_PATH" "$DIGITALKNOB_DIR"/"$DKSCRIPT_NAME"
+		unset DKINIT
+		#cd "$DIGITALKNOB_DIR" #|| dk_error "cd $$DIGITALKNOB_DIR failed!"
+		exec /bin/bash "$DIGITALKNOB_DIR/$DKSCRIPT_NAME" dk_resetAll wipe
 	else	
 		#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 		#:wipe
@@ -47,18 +52,23 @@ dk_removeAll () {
 		#do we need to kill any processes?
 		#do we need to undk_install any apps?
 		#do we need to remove any environment variables?
-		
+		printenv
+
 		cd "$DIGITALKNOB_DIR" #|| dk_error "cd $$DIGITALKNOB_DIR failed!"
-		dk_echo
-		dk_info "DELETING $DKBRANCH_DIR . . . ."
-		rm -r -f "$DKBRANCH_DIR"
-		dk_info "done."
+		
+ 	   
+		dk_validate DKBRANCH_DIR "dk_validateBranch"
+		DKBASH_DIR="${DIGITALKNOB_DIR}/DKBash"	
+		dk_echo "DELETING $DKBRANCH_DIR . . . ."
+		dk_call rm -r -f "$DKBRANCH_DIR" #|| dk_error "dk_call rm -r -f $DKBRANCH_DIR failed"
+		dk_echo "done."
 		
 		# wait for the folders to get deleted
-		sleep 3
-		
+		sleep 5
+
 		if dk_fileExists "$DKBRANCH_DIR"; then
 			dk_error "Oh no, the BRANCH folder is still there! :( "
 		fi
+
 	fi
 }
